######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 24 02:34:51 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += intelliplugin.h printinfo.h shineprint.h
SOURCES += intelliplugin.cpp main.cpp printinfo.cpp shineprint.cpp
